services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cardsight
      POSTGRES_PASSWORD: cardsight
      POSTGRES_DB: cardsight
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
